version: "3.7"
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ttn_lorawan_dev
    volumes:
      - ${DEV_DATA_DIR:-.env/data}/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - ${DEV_DATA_DIR:-.env/data}/redis:/data
    ports:
      - "127.0.0.1:6379:6379"

  stack:
    image: thethingsnetwork/lorawan-stack
    entrypoint: ttn-lw-stack -c /config/ttn-lw-stack-docker.yml
    command: start
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    volumes:
      - ./blob:/srv/ttn-lorawan/public/blob
      - ./config/stack:/config:ro
    env_file:
      - .env/ttn-lw-stack.env
    ports:
      - "0.0.0.0:1881:1881"
      - "0.0.0.0:1882:1882"
      - "0.0.0.0:1883:1883"
      - "0.0.0.0:1884:1884"
      - "0.0.0.0:1885:1885"
      - "0.0.0.0:1887:1887"
      - "0.0.0.0:8881:8881"
      - "0.0.0.0:8882:8882"
      - "0.0.0.0:8883:8883"
      - "0.0.0.0:8884:8884"
      - "0.0.0.0:8885:8885"
      - "0.0.0.0:8887:8887"
      - "0.0.0.0:1700:1700/udp"
