# Identity Server configuration
is:
  database-uri: postgres://root:root@postgres:5432/ttn_lorawan_dev?sslmode=disable
  oauth:
    ui:
      enabled: true
      canonical-url: 'http://localhost:1885/oauth'
    authorize:
      force: false
    client-registry:
      clients:
        console:
          secret: ''  # empty secret for development
          redirect-uris: ['http://localhost:1885/console/oauth/callback']
          rights: ['RIGHT_ALL']
          grants: ['authorization_code', 'refresh_token']
    ui:
      canonical-url: 'http://localhost:1885/oauth'
      is:
        base-url: 'http://localhost:1885/api/v3'

# Console configuration
console:
  oauth:
    client-id: 'console'
    client-secret: ''
    authorize-url: 'http://localhost:1885/oauth/authorize'
    token-url: 'http://localhost:1885/oauth/token'
  ui:
    enabled: true
    canonical-url: 'http://localhost:1885/console'
    is:
      base-url: 'http://localhost:1885/api/v3'
    gs:
      base-url: 'http://localhost:1885/api/v3'
    ns:
      base-url: 'http://localhost:1885/api/v3'
    as:
      base-url: 'http://localhost:1885/api/v3'
    js:
      base-url: 'http://localhost:1885/api/v3'

# HTTP server configuration
http:
  cookie:
    hash-key: '704228a131af1bff5678e5262cac65ca3c62faebeb1219d1a1fdbd9be1c5213b50374cad6eff096d78769310eee07da93ccae1f5f88d2961b19d9e758e83f923'
    block-key: 'cda0a061be0600b723b300bf90a52c13d161521059c48e32970a847009675b6f'
